# --- Google Sheets 연결 정보 ---
[connections.gsheets]
type = "service_account"
project_id = "cobalt-entropy-473808-k8"
private_key_id = "bb43fae21cf7dd51b73c2c09305cbe103d5db55d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDxFuzHdUxFXYhD
+10ZgjrRbgvyam1Mv7ktNco2HGR3zB3S/u+qJVo2p1sV6xoBPyJuieuF8tXuXeQk
QQAAkNRFulyzdgkgimCORc6zKjNU1Gj8owbJPgOHLHEslzkrP/xgPFwKHNEQPLVR
bJRnrW1EDTcrbgOJU5NQjWi02p6FHtLE36TzNgkm9gQB0Oh7C4W5tSYhxdyZjrbJ
rL8boGogI+RgWVX7EzTe3DORoJvKR9XfDmyF60BM70ZO6WF1ScMdL/TmgOfRnvdO
WIysHeCxNZvOYrTeDQm7Xw4QZN6nLHBRuVb86tUKMIwrU+daD4v1mOfYRE7skAVp
1W/9SU8VAgMBAAECggEALvnOT6wHnUF1DngBQznon4ufiM/bdbeqy4geW05Ldjs/
uW/iv4axLhKMcTgi1EjauuqlSW+QZzaEwFqo9zNBJUgDjZVLgHtuBnLMLIVlxJrx
zP4wEZDDi7hpYeyiX07DrHW+YlsMkmsd0lyDizMT5g1kKVJxnnW6L9kp5Ilvl1TS
GzxMDkN1HGdHV6uzWxW2XDtC1l4x2tdGtyOa2K5f0Zlyg/IsOQ3ULqx7Zdg74XvS
32OJO86AIgBCljX3s37EA32RAmo68hbe85zA4HcNXDqUQYXcEljp11myrP03BDBV
+A5F8VTn6ZlBV+p7g3G2qCvXJFyniqNhJSHmQVtBMQKBgQD9rWP8Qrjjk3mxKmDp
FtcguOtvMy6R6wIlqG2T0DJPg72qN54QRKAv6N8wDAPYchLszYWf5rOay6xnY2eu
YVZ204Ri6383+SDzDA6xCcT0OjAF0vyBS40dwe3B9H6afnPoD/Nw4SvHSijerDba
qrXfPClzEuK/EkAIFJnqg9+ahQKBgQDzTAd2qPNmFNLRboYQci5r6Rgy3L+ISWW9
MNEwguG44Wg27wGgDTksRhROsCKdaRo+yrV1F94pRrwrsmz3oCwkZLPVs27B6C7Z
Rc7G/Gqouq7UxfxVmTnTzKp8A3GhaAdFKmC+rZgREqgrDMG3EbAqxkkqFJjuASLD
FH0VZO8vUQKBgQCXOe96KdiIqpkIOchODDSxKCwKPYvMpzm/c1nnnVzwtAu0VrWe
4xpPlVbAENmWBeMsUhUPzvtRE4wykjrz5Mkjy1KHmfZcSuMOoSh89+L26V1Ji47G
EWEN1VdEodl7hljYhfHNYB62DoqwvB9zWgNUEkxvclnEKEAN0SI0gOsi9QKBgQCd
PpVQTs/JOUosC8fgFzwDiIqYTO4Jco6r4UJCnUSwDhch8gVV4VYDVGPJm7Mzk3tf
+/mdbUir2sjBYTdmMAJ3nxJP2wGJl7u3t5N2LivtU4KtiCyXUkn6prvFHSCy1l5k
yIfwlRfEaQ+Bi2QkIu1+J9ufs+JHaTqDZNmXGz4vkQKBgC/0xDcTYsnf3u+i36/s
kglen6dXB3uZMC8zdtKD4D99LXzMu1W4sH7x4O0rLo5In2C/8XdMgxYLgSe5I137
VSz1llGUvlD7tN/rmozu3y2jIVHeUeXms5imlEaoFaaO+QnEca6gmMBRecnMDynD1
UsaPMl6xPskR3drzC3TfXS7P
-----END PRIVATE KEY-----"""
client_email = "diary-app-editor@cobalt-entropy-473808-k8.iam.gserviceaccount.com"
client_id = "115426675707036753339"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x500_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/diary-app-editor%4coboalt-entropy-473808-k8.iam.gserviceaccount.com"

# --- Spotify API 정보 ---
[spotify]
client_id = "8f398f52f872437999214228d73f8d10"
client_secret = "a0eaee2869e24be1b4bb8263f3492cef"

# --- TMDB API 정보 ---
TMDB_API_KEY = "8587d6734fd278ecc05dcbe710c29f9c"
