# --- Spotify API 정보 ---
[spotify]
client_id = "8f398f52f872437999214228d73f8d10"
client_secret = "a0eaee2869e24be1b4bb8263f3492cef"

# --- TMDB API 정보 ---
TMDB_API_KEY = "8587d6734fd278ecc05dcbe710c29f9c"
